name: AchieveOresome
description: Achieve Oresomeness by gathering achievements around the Oresomecraft SMP world!
version: 1.0.0
main: com.oresomecraft.AchieveOresome.AchieveOresome
authors: [azdaspaz818, ScruffyRules]
